### ISSUE TITLE
Missing Builder for ApplicationStateTransitionEvent

### ISSUE THREAD

**Issue by doubtx** [mParticle/mparticle-go-sdk#10]
Hello, seems there is no builder defined for ApplicationStateTranstition event, can you please add one here:
https://github.com/mParticle/mparticle-go-sdk/blob/2e9b78462334672cd0348247dbb6af0120f6544f/events/model_application_state_transition_event.go#L7

Same as it is done here:
https://github.com/mParticle/mparticle-go-sdk/blob/2e9b78462334672cd0348247dbb6af0120f6544f/events/model_session_start_event.go#L10

**Comment by einsteinx2** [comment]
Thanks for reporting this, tracking in internal issue: https://go.mparticle.com/work/SQDSDKS-3661

**Comment by einsteinx2** [comment]
Looks like this was merged back in February (https://github.com/mParticle/mparticle-go-sdk/pull/11, thanks for the PR!), closing this issue.
