### ISSUE TITLE
Unable to install package

### ISSUE THREAD

**Issue by mmuoDev** [mParticle/mparticle-go-sdk#13]
I am unable to install your package, I am having this error - 
```
go get: github.com/mParticle/mparticle-go-sdk@v1.1.2 updating to
        github.com/mParticle/mparticle-go-sdk@v1.1.3: parsing go.mod:
        module declares its path as: event
                but was required as: github.com/mParticle/mparticle-go-sdk
 ```

**Comment by einsteinx2** [comment]
@mmuoDev Thank you for reporting this issue. This should be fixed in the latest update. Please try updating to 1.1.5. If you still have the issue, please re-open this ticket or open a new one. Thanks.
